const categories = ['Parking','Brandstof','Tol','Openbaar vervoer','Taxi','Huurwagen','Boodschappen','Restaurant','Koffie','Hotel','Reizen','Vlucht/Trein','Kantoor','Software','Diensten','Abonnementen','Telecom','Verzekering','Belastingen','Gezondheid','Onderhoud','Cadeaus','Vrije tijd','Aankopen','Overige'];
const $ = (id) => document.getElementById(id);
const ui = { scanBtn:$('scanBtn'), photoBtn:$('photoBtn'), pdfBtn:$('pdfBtn'), exportBtn:$('exportBtn'), photoInput:$('photoInput'), scanner:$('scanner'), video:$('video'), closeCamBtn:$('closeCamBtn'), shootBtn:$('shootBtn'), doneBtn:$('doneBtn'), strip:$('strip'), count:$('count'), review:$('review'), reviewBackBtn:$('reviewBackBtn'), rotateBtn:$('rotateBtn'), redetectBtn:$('redetectBtn'), enhanceBtn:$('enhanceBtn'), acceptBtn:$('acceptBtn'), stage:$('stage'), canvas:$('canvas'), overlay:$('overlay'), poly:$('poly'), sheet:$('sheet'), preview:$('preview'), date:$('date'), amount:$('amount'), desc:$('desc'), cat:$('cat'), notes:$('notes'), saveBtn:$('saveBtn'), total:$('total'), list:$('list'), work:$('work'), toast:$('toast') };
let expenses = JSON.parse(localStorage.visaExpenses || '[]');
let pages = [], stream = null, current = '', img = null, idx = 0, rot = 0, enhanced = false, quad = [], drag = -1, uploadFlow = false;
ui.cat.innerHTML = categories.map(c => `<option>${c}</option>`).join(''); ui.date.valueAsDate = new Date(); render();
ui.scanBtn.onclick = openCam; ui.photoBtn.onclick = () => ui.photoInput.click(); ui.pdfBtn.onclick = () => showToast('PDF upload is beperkt op GitHub Pages. Gebruik best foto of camera.'); ui.exportBtn.onclick = exportPdf; ui.closeCamBtn.onclick = closeCam; ui.shootBtn.onclick = shoot; ui.doneBtn.onclick = finishScan; ui.reviewBackBtn.onclick = backFromReview; ui.rotateBtn.onclick = rotate; ui.redetectBtn.onclick = () => detect(true); ui.enhanceBtn.onclick = () => { enhanced = !enhanced; draw(); detect(true); }; ui.acceptBtn.onclick = acceptCrop; ui.saveBtn.onclick = saveExpense; ui.sheet.onclick = e => { if (e.target === ui.sheet) ui.sheet.classList.remove('on'); }; ui.photoInput.onchange = uploadPhoto; window.addEventListener('resize', paint);
function showToast(m){ui.toast.textContent=m;ui.toast.classList.add('show');clearTimeout(ui.toast.t);ui.toast.t=setTimeout(()=>ui.toast.classList.remove('show'),2400)}
async function openCam(){pages=[];uploadFlow=false;thumbs();ui.scanner.classList.add('on');try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1920},height:{ideal:1080}},audio:false});ui.video.srcObject=stream}catch{ui.scanner.classList.remove('on');showToast('Camera niet beschikbaar')}}
function closeCam(){if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}ui.scanner.classList.remove('on')}
function shoot(){const c=ui.work;c.width=ui.video.videoWidth||1280;c.height=ui.video.videoHeight||720;c.getContext('2d').drawImage(ui.video,0,0,c.width,c.height);pages.push(c.toDataURL('image/jpeg',.94));thumbs();openReview(pages.length-1,false)}
function thumbs(){ui.count.textContent=pages.length;ui.doneBtn.style.visibility=pages.length?'visible':'hidden';ui.strip.innerHTML=pages.map((p,i)=>`<div class="mini"><img src="${p}" onclick="openReview(${i},false)"><button onclick="event.stopPropagation();pages.splice(${i},1);thumbs()">x</button></div>`).join('')}
function finishScan(){if(!pages.length)return closeCam();closeCam();stitch(pages).then(u=>{current=u;openForm()})}
function uploadPhoto(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{pages=[r.result];uploadFlow=true;openReview(0,true)};r.readAsDataURL(f);e.target.value=''}
function openReview(i,fromUpload){idx=i;uploadFlow=fromUpload;rot=0;enhanced=false;img=new Image();img.onload=()=>{ui.scanner.classList.remove('on');ui.review.classList.add('on');draw();detect(false);dragHandles();showToast('Hoeken automatisch gevonden. Controleer en bevestig.')};img.src=pages[i]}
function backFromReview(){ui.review.classList.remove('on');if(!uploadFlow)ui.scanner.classList.add('on')}
function draw(){let w=img.width,h=img.height;if(rot%180)[w,h]=[h,w];ui.canvas.width=w;ui.canvas.height=h;const x=ui.canvas.getContext('2d');x.save();x.translate(w/2,h/2);x.rotate(rot*Math.PI/180);x.drawImage(img,-img.width/2,-img.height/2);x.restore();if(enhanced){const d=x.getImageData(0,0,w,h),p=d.data;for(let i=0;i<p.length;i+=4)for(let k=0;k<3;k++)p[i+k]=Math.max(0,Math.min(255,1.6*(p[i+k]-128)+150));x.putImageData(d,0,0)}}
function rotate(){rot=(rot+90)%360;draw();detect(true)}
function detect(manual){const W=ui.canvas.width,H=ui.canvas.height,data=ui.canvas.getContext('2d').getImageData(0,0,W,H).data;quad=autoDetectDocument(W,H,data).quad;paint();if(manual)showToast('Hoeken opnieuw gezocht')}

function autoDetectDocument(W,H,data){const contourDoc=detectContourDocument(W,H,data);if(contourDoc)return contourDoc;const brightDoc=detectBrightDocument(W,H,data);return brightDoc||defaultDocumentCrop(W,H)}
function detectContourDocument(W,H,data){const maxSize=760;const scale=Math.min(1,maxSize/Math.max(W,H));const w=Math.max(1,Math.round(W*scale));const h=Math.max(1,Math.round(H*scale));const gray=new Uint8ClampedArray(w*h);for(let y=0;y<h;y++){const sy=Math.min(H-1,Math.round(y/scale));for(let x=0;x<w;x++){const sx=Math.min(W-1,Math.round(x/scale));const i=(sy*W+sx)*4;gray[y*w+x]=0.299*data[i]+0.587*data[i+1]+0.114*data[i+2]}}const mags=[];const edge=new Uint8Array(w*h);for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++){const p=y*w+x;const gx=-gray[p-w-1]+gray[p-w+1]-2*gray[p-1]+2*gray[p+1]-gray[p+w-1]+gray[p+w+1];const gy=-gray[p-w-1]-2*gray[p-w]-gray[p-w+1]+gray[p+w-1]+2*gray[p+w]+gray[p+w+1];mags.push(Math.hypot(gx,gy))}mags.sort((a,b)=>a-b);const threshold=Math.max(38,mags[Math.floor(mags.length*0.84)]||0);for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++){const p=y*w+x;const gx=-gray[p-w-1]+gray[p-w+1]-2*gray[p-1]+2*gray[p+1]-gray[p+w-1]+gray[p+w+1];const gy=-gray[p-w-1]-2*gray[p-w]-gray[p-w+1]+gray[p+w-1]+2*gray[p+w]+gray[p+w+1];if(Math.hypot(gx,gy)>=threshold){for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++)edge[p+dy*w+dx]=1}}const seen=new Uint8Array(w*h);let best=null;const q=[];for(let y=2;y<h-2;y++)for(let x=2;x<w-2;x++){const start=y*w+x;if(!edge[start]||seen[start])continue;let count=0,minX=x,minY=y,maxX=x,maxY=y;q.length=0;q.push(start);seen[start]=1;for(let qi=0;qi<q.length;qi++){const p=q[qi],px=p%w,py=(p/w)|0;count++;minX=Math.min(minX,px);minY=Math.min(minY,py);maxX=Math.max(maxX,px);maxY=Math.max(maxY,py);const ns=[p-1,p+1,p-w,p+w,p-w-1,p-w+1,p+w-1,p+w+1];for(const n of ns)if(n>0&&n<edge.length&&edge[n]&&!seen[n]){seen[n]=1;q.push(n)}}const bw=maxX-minX,bh=maxY-minY;const area=bw*bh;const touchesBorder=minX<4||minY<4||maxX>w-5||maxY>h-5;if(!touchesBorder&&count>70&&area>w*h*0.08&&(!best||area>best.area))best={minX,minY,maxX,maxY,area}}if(!best)return null;const pad=Math.round(Math.min(w,h)*0.018);const contourPoints=[];for(let y=Math.max(0,best.minY-pad);y<=Math.min(h-1,best.maxY+pad);y++)for(let x=Math.max(0,best.minX-pad);x<=Math.min(w-1,best.maxX+pad);x++)if(edge[y*w+x])contourPoints.push([x/scale,y/scale]);return pointsToDocument(W,H,contourPoints,Math.round(Math.min(W,H)*0.014))}
function detectBrightDocument(W,H,data){const step=Math.max(2,Math.floor(Math.min(W,H)/420));const samples=[],hits=[];for(let y=0;y<H;y+=step)for(let x=0;x<W;x+=step){const i=(y*W+x)*4;samples.push(0.299*data[i]+0.587*data[i+1]+0.114*data[i+2])}samples.sort((a,b)=>a-b);const low=samples[Math.floor(samples.length*0.18)]||0;const high=samples[Math.floor(samples.length*0.9)]||255;const threshold=Math.max(145,low+(high-low)*0.52);for(let y=0;y<H;y+=step)for(let x=0;x<W;x+=step){const i=(y*W+x)*4;const r=data[i],g=data[i+1],b=data[i+2];const luma=0.299*r+0.587*g+0.114*b;const saturation=Math.max(r,g,b)-Math.min(r,g,b);if(luma>=threshold&&(saturation<92||luma>210))hits.push([x,y])}return pointsToDocument(W,H,hits,Math.round(Math.min(W,H)*0.018))}
function pointsToDocument(W,H,points,pad){if(points.length<40)return null;let minX=W,minY=H,maxX=0,maxY=0;let tl=null,tr=null,br=null,bl=null;let tlScore=Infinity,trScore=-Infinity,brScore=-Infinity,blScore=Infinity;points.forEach(([x,y])=>{minX=Math.min(minX,x);minY=Math.min(minY,y);maxX=Math.max(maxX,x);maxY=Math.max(maxY,y);const sum=x+y;const diff=x-y;if(sum<tlScore){tlScore=sum;tl={x,y}}if(diff>trScore){trScore=diff;tr={x,y}}if(sum>brScore){brScore=sum;br={x,y}}if(diff<blScore){blScore=diff;bl={x,y}}});const rect=sanitizeCropRect(W,H,{x:minX-pad,y:minY-pad,w:maxX-minX+pad*2,h:maxY-minY+pad*2});const candidateQuad=expandQuad([tl,tr,br,bl],W,H,pad);if(!isValidQuad(W,H,candidateQuad))return rectToDocument(rect);return{rect,quad:candidateQuad}}
function defaultCropRect(W,H){const pad=Math.max(8,Math.round(Math.min(W,H)*0.03));return{x:pad,y:pad,w:W-pad*2,h:H-pad*2}}
function sanitizeCropRect(W,H,rect){const x=Math.max(0,Math.round(rect.x));const y=Math.max(0,Math.round(rect.y));const w=Math.min(W-x,Math.round(rect.w));const h=Math.min(H-y,Math.round(rect.h));const area=w*h;const fullArea=W*H;if(w<W*0.32||h<H*0.32||area<fullArea*0.22)return defaultCropRect(W,H);return{x,y,w,h}}
function rectToQuad(rect){return[{x:rect.x,y:rect.y},{x:rect.x+rect.w,y:rect.y},{x:rect.x+rect.w,y:rect.y+rect.h},{x:rect.x,y:rect.y+rect.h}]}
function rectToDocument(rect){return{rect,quad:rectToQuad(rect)}}
function defaultDocumentCrop(W,H){return rectToDocument(defaultCropRect(W,H))}
function expandQuad(candidateQuad,W,H,pad){if(!candidateQuad.every(Boolean))return null;const cx=candidateQuad.reduce((sum,p)=>sum+p.x,0)/4;const cy=candidateQuad.reduce((sum,p)=>sum+p.y,0)/4;return candidateQuad.map(p=>{const dx=p.x-cx;const dy=p.y-cy;const len=Math.hypot(dx,dy)||1;return{x:clamp(p.x+dx/len*pad,0,W),y:clamp(p.y+dy/len*pad,0,H)}})}
function isValidQuad(W,H,candidateQuad){if(!candidateQuad||!candidateQuad.every(p=>p&&Number.isFinite(p.x)&&Number.isFinite(p.y)))return false;const area=Math.abs(polyArea(candidateQuad));if(area<W*H*0.2)return false;const top=dist(candidateQuad[0],candidateQuad[1]);const right=dist(candidateQuad[1],candidateQuad[2]);const bottom=dist(candidateQuad[2],candidateQuad[3]);const left=dist(candidateQuad[3],candidateQuad[0]);return Math.min(top,right,bottom,left)>Math.min(W,H)*0.12}
function polyArea(q){return q.reduce((s,p,i)=>{const n=q[(i+1)%q.length];return s+p.x*n.y-n.x*p.y},0)/2}function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function paint(){if(!quad.length)return;const r=ui.canvas.getBoundingClientRect(),sr=ui.stage.getBoundingClientRect();ui.overlay.style.left=(r.left-sr.left)+'px';ui.overlay.style.top=(r.top-sr.top)+'px';ui.overlay.style.width=r.width+'px';ui.overlay.style.height=r.height+'px';ui.overlay.setAttribute('viewBox',`0 0 ${r.width} ${r.height}`);const pts=quad.map(p=>[p.x*r.width/ui.canvas.width,p.y*r.height/ui.canvas.height]);ui.poly.setAttribute('points',pts.map(p=>p.join(',')).join(' '));pts.forEach(([x,y],i)=>{const h=$('h'+i);h.setAttribute('cx',x);h.setAttribute('cy',y);h.style.pointerEvents='all'})}
function dragHandles(){ui.overlay.style.pointerEvents='all';for(let i=0;i<4;i++)$('h'+i).onpointerdown=e=>{drag=i;e.preventDefault();ui.overlay.setPointerCapture(e.pointerId)};ui.overlay.onpointermove=e=>{if(drag<0)return;const r=ui.canvas.getBoundingClientRect();quad[drag]={x:clamp((e.clientX-r.left)*ui.canvas.width/r.width,0,ui.canvas.width),y:clamp((e.clientY-r.top)*ui.canvas.height/r.height,0,ui.canvas.height)};paint()};ui.overlay.onpointerup=()=>drag=-1;ui.overlay.onpointercancel=()=>drag=-1}
function acceptCrop(){pages[idx]=warp(ui.canvas,quad);thumbs();ui.review.classList.remove('on');if(uploadFlow){current=pages[idx];openForm()}else ui.scanner.classList.add('on')}
function warp(src,q){const W=Math.round(Math.max(dist(q[0],q[1]),dist(q[2],q[3]))),H=Math.round(Math.max(dist(q[1],q[2]),dist(q[3],q[0]))),scale=Math.min(1,1700/Math.max(W,H)),w=Math.max(1,Math.round(W*scale)),h=Math.max(1,Math.round(H*scale)),out=document.createElement('canvas');out.width=w;out.height=h;const ctx=out.getContext('2d'),sd=src.getContext('2d').getImageData(0,0,src.width,src.height),od=ctx.createImageData(w,h),m=matrix([{x:0,y:0},{x:w-1,y:0},{x:w-1,y:h-1},{x:0,y:h-1}],q);for(let y=0;y<h;y++)for(let x=0;x<w;x++){const z=m[6]*x+m[7]*y+1,sx=(m[0]*x+m[1]*y+m[2])/z,sy=(m[3]*x+m[4]*y+m[5])/z,c=sample(sd,sx,sy),i=(y*w+x)*4;od.data[i]=c[0];od.data[i+1]=c[1];od.data[i+2]=c[2];od.data[i+3]=255}ctx.putImageData(od,0,0);return out.toDataURL('image/jpeg',.93)}
function sample(im,x,y){x=clamp(x,0,im.width-1);y=clamp(y,0,im.height-1);const x0=x|0,y0=y|0,x1=Math.min(im.width-1,x0+1),y1=Math.min(im.height-1,y0+1),dx=x-x0,dy=y-y0,out=[0,0,0];for(let c=0;c<3;c++){const p=(xx,yy)=>im.data[(yy*im.width+xx)*4+c],top=p(x0,y0)*(1-dx)+p(x1,y0)*dx,bot=p(x0,y1)*(1-dx)+p(x1,y1)*dx;out[c]=top*(1-dy)+bot*dy}return out}
function matrix(a,b){const A=[],B=[];for(let i=0;i<4;i++){const x=a[i].x,y=a[i].y,u=b[i].x,v=b[i].y;A.push([x,y,1,0,0,0,-u*x,-u*y]);B.push(u);A.push([0,0,0,x,y,1,-v*x,-v*y]);B.push(v)}return solve(A,B)||[1,0,0,0,1,0,0,0]}
function solve(A,b){const n=b.length,M=A.map((r,i)=>r.concat(b[i]));for(let c=0;c<n;c++){let p=c;for(let r=c+1;r<n;r++)if(Math.abs(M[r][c])>Math.abs(M[p][c]))p=r;if(Math.abs(M[p][c])<1e-9)return null;[M[c],M[p]]=[M[p],M[c]];const v=M[c][c];for(let j=c;j<=n;j++)M[c][j]/=v;for(let r=0;r<n;r++){if(r===c)continue;const f=M[r][c];for(let j=c;j<=n;j++)M[r][j]-=f*M[c][j]}}return M.map(r=>r[n])}
function stitch(arr){return new Promise(res=>{let imgs=[],loaded=0;arr.forEach((u,i)=>{const im=new Image();im.onload=()=>{imgs[i]=im;if(++loaded===arr.length){const W=Math.max(...imgs.map(x=>x.width)),H=imgs.reduce((s,x)=>s+x.height+18,0),c=ui.work,x=c.getContext('2d');c.width=W;c.height=H;x.fillStyle='#eee';x.fillRect(0,0,W,H);let y=0;imgs.forEach(im=>{x.drawImage(im,(W-im.width)/2,y);y+=im.height+18});res(c.toDataURL('image/jpeg',.9))}};im.src=u})})}
function openForm(){ui.preview.src=current;ui.date.valueAsDate=new Date();ui.amount.value='';ui.desc.value='';ui.notes.value='';ui.sheet.classList.add('on')}
function saveExpense(){const a=parseFloat(ui.amount.value),d=ui.desc.value.trim();if(!a||!d)return showToast('Vul bedrag en beschrijving in');expenses.unshift({id:Date.now(),date:ui.date.value,amount:a,desc:d,cat:ui.cat.value,notes:ui.notes.value,img:current});localStorage.visaExpenses=JSON.stringify(expenses);ui.sheet.classList.remove('on');render();showToast('Uitgave toegevoegd')}
function render(){ui.total.textContent='EUR '+expenses.reduce((s,e)=>s+Number(e.amount),0).toFixed(2);ui.list.innerHTML=expenses.length?expenses.map(e=>`<article class="expense"><div class="row"><div class="thumb">${e.img?`<img src="${e.img}">`:'Doc'}</div><div class="body"><div class="line1"><div class="desc">${esc(e.desc)}</div><div class="amt">EUR ${Number(e.amount).toFixed(2)}</div></div><div class="meta">${fmt(e.date)}</div><span class="cat">${esc(e.cat)}</span>${e.notes?`<div class="note">${esc(e.notes)}</div>`:''}</div></div><button class="del" onclick="deleteExpense(${e.id})">Verwijderen</button></article>`).join(''):'<div class="empty">Nog geen uitgaven</div>'}
function deleteExpense(id){expenses=expenses.filter(e=>e.id!==id);localStorage.visaExpenses=JSON.stringify(expenses);render()}
function fmt(d){if(!d)return'';const p=d.split('-');return p.length===3?`${p[2]}/${p[1]}/${p[0]}`:d}function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function exportPdf(){if(!expenses.length)return showToast('Geen uitgaven');const{jsPDF}=window.jspdf,doc=new jsPDF();expenses.forEach((e,i)=>{if(i)doc.addPage();doc.text(e.desc,10,15);doc.text('EUR '+Number(e.amount).toFixed(2),10,25);doc.text(e.cat,10,35);if(e.img)doc.addImage(e.img,'JPEG',10,45,180,120)});doc.save('visatracker.pdf')}
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
