const categories = ['Parking','Brandstof','Tol','Openbaar vervoer','Taxi','Huurwagen','Boodschappen','Restaurant','Koffie','Hotel','Reizen','Vlucht/Trein','Kantoor','Software','Diensten','Abonnementen','Telecom','Verzekering','Belastingen','Gezondheid','Onderhoud','Cadeaus','Vrije tijd','Aankopen','Overige'];
const $ = (id) => document.getElementById(id);
const ui = { scanBtn:$('scanBtn'), photoBtn:$('photoBtn'), pdfBtn:$('pdfBtn'), exportBtn:$('exportBtn'), photoInput:$('photoInput'), scanner:$('scanner'), video:$('video'), closeCamBtn:$('closeCamBtn'), shootBtn:$('shootBtn'), doneBtn:$('doneBtn'), strip:$('strip'), count:$('count'), review:$('review'), reviewBackBtn:$('reviewBackBtn'), rotateBtn:$('rotateBtn'), redetectBtn:$('redetectBtn'), enhanceBtn:$('enhanceBtn'), acceptBtn:$('acceptBtn'), stage:$('stage'), canvas:$('canvas'), overlay:$('overlay'), poly:$('poly'), sheet:$('sheet'), preview:$('preview'), date:$('date'), amount:$('amount'), desc:$('desc'), cat:$('cat'), notes:$('notes'), saveBtn:$('saveBtn'), total:$('total'), list:$('list'), work:$('work'), toast:$('toast') };
let expenses = JSON.parse(localStorage.visaExpenses || '[]');
let pages = [], stream = null, current = '', img = null, idx = 0, rot = 0, enhanced = false, quad = [], drag = -1, uploadFlow = false;
ui.cat.innerHTML = categories.map(c => `<option>${c}</option>`).join(''); ui.date.valueAsDate = new Date(); render();
ui.scanBtn.onclick = openCam; ui.photoBtn.onclick = () => ui.photoInput.click(); ui.pdfBtn.onclick = () => showToast('PDF upload is beperkt op GitHub Pages. Gebruik best foto of camera.'); ui.exportBtn.onclick = exportPdf; ui.closeCamBtn.onclick = closeCam; ui.shootBtn.onclick = shoot; ui.doneBtn.onclick = finishScan; ui.reviewBackBtn.onclick = backFromReview; ui.rotateBtn.onclick = rotate; ui.redetectBtn.onclick = () => detect(true); ui.enhanceBtn.onclick = () => { enhanced = !enhanced; draw(); detect(true); }; ui.acceptBtn.onclick = acceptCrop; ui.saveBtn.onclick = saveExpense; ui.sheet.onclick = e => { if (e.target === ui.sheet) ui.sheet.classList.remove('on'); }; ui.photoInput.onchange = uploadPhoto; window.addEventListener('resize', paint);
function showToast(m){ui.toast.textContent=m;ui.toast.classList.add('show');clearTimeout(ui.toast.t);ui.toast.t=setTimeout(()=>ui.toast.classList.remove('show'),2400)}
async function openCam(){pages=[];uploadFlow=false;thumbs();ui.scanner.classList.add('on');try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1920},height:{ideal:1080}},audio:false});ui.video.srcObject=stream}catch{ui.scanner.classList.remove('on');showToast('Camera niet beschikbaar')}}
function closeCam(){if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}ui.scanner.classList.remove('on')}
function shoot(){const c=ui.work;c.width=ui.video.videoWidth||1280;c.height=ui.video.videoHeight||720;c.getContext('2d').drawImage(ui.video,0,0,c.width,c.height);pages.push(c.toDataURL('image/jpeg',.94));thumbs();openReview(pages.length-1,false)}
function thumbs(){ui.count.textContent=pages.length;ui.doneBtn.style.visibility=pages.length?'visible':'hidden';ui.strip.innerHTML=pages.map((p,i)=>`<div class="mini"><img src="${p}" onclick="openReview(${i},false)"><button onclick="event.stopPropagation();pages.splice(${i},1);thumbs()">x</button></div>`).join('')}
function finishScan(){if(!pages.length)return closeCam();closeCam();stitch(pages).then(u=>{current=u;openForm()})}
function uploadPhoto(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{pages=[r.result];uploadFlow=true;openReview(0,true)};r.readAsDataURL(f);e.target.value=''}
function openReview(i,fromUpload){idx=i;uploadFlow=fromUpload;rot=0;enhanced=false;img=new Image();img.onload=()=>{ui.scanner.classList.remove('on');ui.review.classList.add('on');draw();detect(false);dragHandles();showToast('Hoeken automatisch gevonden. Controleer en bevestig.')};img.src=pages[i]}
function backFromReview(){ui.review.classList.remove('on');if(!uploadFlow)ui.scanner.classList.add('on')}
function draw(){let w=img.width,h=img.height;if(rot%180)[w,h]=[h,w];ui.canvas.width=w;ui.canvas.height=h;const x=ui.canvas.getContext('2d');x.save();x.translate(w/2,h/2);x.rotate(rot*Math.PI/180);x.drawImage(img,-img.width/2,-img.height/2);x.restore();if(enhanced){const d=x.getImageData(0,0,w,h),p=d.data;for(let i=0;i<p.length;i+=4)for(let k=0;k<3;k++)p[i+k]=Math.max(0,Math.min(255,1.6*(p[i+k]-128)+150));x.putImageData(d,0,0)}}
function rotate(){rot=(rot+90)%360;draw();detect(true)}
function detect(manual){const W=ui.canvas.width,H=ui.canvas.height,data=ui.canvas.getContext('2d').getImageData(0,0,W,H).data;quad=scanLikePaper(W,H,data)||brightPaper(W,H,data)||defaultQuad(W,H);paint();if(manual)showToast('Hoeken opnieuw gezocht')}

function scanLikePaper(W,H,data){
  const S=Math.min(1,820/Math.max(W,H)),w=Math.max(1,Math.round(W*S)),h=Math.max(1,Math.round(H*S));
  const gray=new Float32Array(w*h),blur=new Float32Array(w*h),scoreVals=[];
  for(let y=0;y<h;y++)for(let x=0;x<w;x++){const sx=Math.min(W-1,Math.round(x/S)),sy=Math.min(H-1,Math.round(y/S)),i=(sy*W+sx)*4;gray[y*w+x]=.299*data[i]+.587*data[i+1]+.114*data[i+2]}
  for(let y=0;y<h;y++)for(let x=0;x<w;x++){let sum=0,n=0;for(let dy=-3;dy<=3;dy++)for(let dx=-3;dx<=3;dx++){const xx=x+dx,yy=y+dy;if(xx>=0&&yy>=0&&xx<w&&yy<h){sum+=gray[yy*w+xx];n++}}blur[y*w+x]=sum/n}
  const edge=new Uint8Array(w*h);
  for(let y=2;y<h-2;y++)for(let x=2;x<w-2;x++){
    const p=y*w+x;
    const gx=-blur[p-w-1]+blur[p-w+1]-2*blur[p-1]+2*blur[p+1]-blur[p+w-1]+blur[p+w+1];
    const gy=-blur[p-w-1]-2*blur[p-w]-blur[p-w+1]+blur[p+w-1]+2*blur[p+w]+blur[p+w+1];
    const grad=Math.hypot(gx,gy);
    const local=Math.abs(gray[p]-blur[p]);
    const cross=Math.max(Math.abs(avg(gray,w,h,x-10,y,x-3,y)-avg(gray,w,h,x+3,y,x+10,y)),Math.abs(avg(gray,w,h,x,y-10,x,y-3)-avg(gray,w,h,x,y+3,x,y+10)));
    const val=grad+local*1.9+cross*2.2;
    scoreVals.push(val);
  }
  scoreVals.sort((a,b)=>a-b);const th=Math.max(22,scoreVals[Math.floor(scoreVals.length*.76)]||0);
  for(let y=2;y<h-2;y++)for(let x=2;x<w-2;x++){
    const p=y*w+x;
    const gx=-blur[p-w-1]+blur[p-w+1]-2*blur[p-1]+2*blur[p+1]-blur[p+w-1]+blur[p+w+1];
    const gy=-blur[p-w-1]-2*blur[p-w]-blur[p-w+1]+blur[p+w-1]+2*blur[p+w]+blur[p+w+1];
    const grad=Math.hypot(gx,gy),local=Math.abs(gray[p]-blur[p]);
    const cross=Math.max(Math.abs(avg(gray,w,h,x-10,y,x-3,y)-avg(gray,w,h,x+3,y,x+10,y)),Math.abs(avg(gray,w,h,x,y-10,x,y-3)-avg(gray,w,h,x,y+3,x,y+10)));
    if(grad+local*1.9+cross*2.2>=th)edge[p]=1;
  }
  closeEdges(edge,w,h,2);
  const component=bestComponent(edge,w,h);
  if(component){const pts=[];for(let y=component.minY;y<=component.maxY;y++)for(let x=component.minX;x<=component.maxX;x++)if(edge[y*w+x])pts.push({x:x/S,y:y/S});const q=cornerExtremes(W,H,pts);if(q)return q}
  const all=[];for(let y=4;y<h-4;y++)for(let x=4;x<w-4;x++)if(edge[y*w+x])all.push({x:x/S,y:y/S});return cornerExtremes(W,H,all);
}
function avg(a,w,h,x1,y1,x2,y2){x1=clamp(Math.round(x1),0,w-1);x2=clamp(Math.round(x2),0,w-1);y1=clamp(Math.round(y1),0,h-1);y2=clamp(Math.round(y2),0,h-1);let s=0,n=0;for(let y=Math.min(y1,y2);y<=Math.max(y1,y2);y++)for(let x=Math.min(x1,x2);x<=Math.max(x1,x2);x++){s+=a[y*w+x];n++}return n?s/n:0}
function closeEdges(edge,w,h,rounds){for(let r=0;r<rounds;r++){const copy=edge.slice();for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++){const p=y*w+x;if(copy[p])continue;let n=0;for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++)n+=copy[p+dy*w+dx];if(n>=2)edge[p]=1}}for(let r=0;r<1;r++){const copy=edge.slice();for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++){const p=y*w+x;if(!copy[p])continue;let n=0;for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++)n+=copy[p+dy*w+dx];if(n<2)edge[p]=0}}}
function bestComponent(edge,w,h){const seen=new Uint8Array(w*h),queue=[];let best=null;for(let y=2;y<h-2;y++)for(let x=2;x<w-2;x++){const start=y*w+x;if(!edge[start]||seen[start])continue;let count=0,minX=x,minY=y,maxX=x,maxY=y;queue.length=0;queue.push(start);seen[start]=1;for(let qi=0;qi<queue.length;qi++){const p=queue[qi],px=p%w,py=p/w|0;count++;minX=Math.min(minX,px);maxX=Math.max(maxX,px);minY=Math.min(minY,py);maxY=Math.max(maxY,py);for(const n of [p-1,p+1,p-w,p+w,p-w-1,p-w+1,p+w-1,p+w+1])if(n>0&&n<edge.length&&edge[n]&&!seen[n]){seen[n]=1;queue.push(n)}}const bw=maxX-minX,bh=maxY-minY,area=bw*bh,frac=area/(w*h),aspect=bw/Math.max(1,bh),centerPenalty=Math.abs((minX+maxX)/2-w/2)/w+Math.abs((minY+maxY)/2-h/2)/h,border=minX<2||minY<2||maxX>w-3||maxY>h-3;if(count>70&&frac>.08&&frac<.95&&aspect>.35&&aspect<3.2&&!border){const score=area*(1-centerPenalty*.75)+count*4;if(!best||score>best.score)best={minX,minY,maxX,maxY,score}}}return best}
function brightPaper(W,H,data){const step=Math.max(2,Math.floor(Math.min(W,H)/520)),pts=[];for(let y=0;y<H;y+=step)for(let x=0;x<W;x+=step){const i=(y*W+x)*4,l=.299*data[i]+.587*data[i+1]+.114*data[i+2],sat=Math.max(data[i],data[i+1],data[i+2])-Math.min(data[i],data[i+1],data[i+2]);if(l>176&&(sat<72||l>226))pts.push({x,y})}return cornerExtremes(W,H,pts)}
function cornerExtremes(W,H,pts){if(pts.length<45)return null;let minX=W,minY=H,maxX=0,maxY=0,tl,tr,br,bl,tls=1e9,trs=-1e9,brs=-1e9,bls=1e9;for(const p of pts){minX=Math.min(minX,p.x);maxX=Math.max(maxX,p.x);minY=Math.min(minY,p.y);maxY=Math.max(maxY,p.y);const s=p.x+p.y,d=p.x-p.y;if(s<tls){tls=s;tl=p}if(d>trs){trs=d;tr=p}if(s>brs){brs=s;br=p}if(d<bls){bls=d;bl=p}}let q=[tl,tr,br,bl].map(p=>({x:clamp(p.x,0,W),y:clamp(p.y,0,H)}));if(!validQuad(W,H,q)){const pad=Math.min(W,H)*.018;q=[{x:minX-pad,y:minY-pad},{x:maxX+pad,y:minY-pad},{x:maxX+pad,y:maxY+pad},{x:minX-pad,y:maxY+pad}].map(p=>({x:clamp(p.x,0,W),y:clamp(p.y,0,H)}))}return validQuad(W,H,q)?q:null}
function validQuad(W,H,q){const a=Math.abs(polyArea(q));const minSide=Math.min(dist(q[0],q[1]),dist(q[1],q[2]),dist(q[2],q[3]),dist(q[3],q[0]));return a>W*H*.12&&a<W*H*.985&&minSide>Math.min(W,H)*.1}
function defaultQuad(W,H){const x=W*.06,y=H*.05;return[{x,y},{x:W-x,y},{x:W-x,y:H-y},{x,y:H-y}]}
function polyArea(q){return q.reduce((s,p,i)=>{const n=q[(i+1)%q.length];return s+p.x*n.y-n.x*p.y},0)/2}function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function paint(){if(!quad.length)return;const r=ui.canvas.getBoundingClientRect(),sr=ui.stage.getBoundingClientRect();ui.overlay.style.left=(r.left-sr.left)+'px';ui.overlay.style.top=(r.top-sr.top)+'px';ui.overlay.style.width=r.width+'px';ui.overlay.style.height=r.height+'px';ui.overlay.setAttribute('viewBox',`0 0 ${r.width} ${r.height}`);const pts=quad.map(p=>[p.x*r.width/ui.canvas.width,p.y*r.height/ui.canvas.height]);ui.poly.setAttribute('points',pts.map(p=>p.join(',')).join(' '));pts.forEach(([x,y],i)=>{const h=$('h'+i);h.setAttribute('cx',x);h.setAttribute('cy',y);h.style.pointerEvents='all'})}
function dragHandles(){ui.overlay.style.pointerEvents='all';for(let i=0;i<4;i++)$('h'+i).onpointerdown=e=>{drag=i;e.preventDefault();ui.overlay.setPointerCapture(e.pointerId)};ui.overlay.onpointermove=e=>{if(drag<0)return;const r=ui.canvas.getBoundingClientRect();quad[drag]={x:clamp((e.clientX-r.left)*ui.canvas.width/r.width,0,ui.canvas.width),y:clamp((e.clientY-r.top)*ui.canvas.height/r.height,0,ui.canvas.height)};paint()};ui.overlay.onpointerup=()=>drag=-1;ui.overlay.onpointercancel=()=>drag=-1}
function acceptCrop(){pages[idx]=warp(ui.canvas,quad);thumbs();ui.review.classList.remove('on');if(uploadFlow){current=pages[idx];openForm()}else ui.scanner.classList.add('on')}
function warp(src,q){const W=Math.round(Math.max(dist(q[0],q[1]),dist(q[2],q[3]))),H=Math.round(Math.max(dist(q[1],q[2]),dist(q[3],q[0]))),scale=Math.min(1,1700/Math.max(W,H)),w=Math.max(1,Math.round(W*scale)),h=Math.max(1,Math.round(H*scale)),out=document.createElement('canvas');out.width=w;out.height=h;const ctx=out.getContext('2d'),sd=src.getContext('2d').getImageData(0,0,src.width,src.height),od=ctx.createImageData(w,h),m=matrix([{x:0,y:0},{x:w-1,y:0},{x:w-1,y:h-1},{x:0,y:h-1}],q);for(let y=0;y<h;y++)for(let x=0;x<w;x++){const z=m[6]*x+m[7]*y+1,sx=(m[0]*x+m[1]*y+m[2])/z,sy=(m[3]*x+m[4]*y+m[5])/z,c=sample(sd,sx,sy),i=(y*w+x)*4;od.data[i]=c[0];od.data[i+1]=c[1];od.data[i+2]=c[2];od.data[i+3]=255}ctx.putImageData(od,0,0);return out.toDataURL('image/jpeg',.93)}
function sample(im,x,y){x=clamp(x,0,im.width-1);y=clamp(y,0,im.height-1);const x0=x|0,y0=y|0,x1=Math.min(im.width-1,x0+1),y1=Math.min(im.height-1,y0+1),dx=x-x0,dy=y-y0,out=[0,0,0];for(let c=0;c<3;c++){const p=(xx,yy)=>im.data[(yy*im.width+xx)*4+c],top=p(x0,y0)*(1-dx)+p(x1,y0)*dx,bot=p(x0,y1)*(1-dx)+p(x1,y1)*dx;out[c]=top*(1-dy)+bot*dy}return out}
function matrix(a,b){const A=[],B=[];for(let i=0;i<4;i++){const x=a[i].x,y=a[i].y,u=b[i].x,v=b[i].y;A.push([x,y,1,0,0,0,-u*x,-u*y]);B.push(u);A.push([0,0,0,x,y,1,-v*x,-v*y]);B.push(v)}return solve(A,B)||[1,0,0,0,1,0,0,0]}
function solve(A,b){const n=b.length,M=A.map((r,i)=>r.concat(b[i]));for(let c=0;c<n;c++){let p=c;for(let r=c+1;r<n;r++)if(Math.abs(M[r][c])>Math.abs(M[p][c]))p=r;if(Math.abs(M[p][c])<1e-9)return null;[M[c],M[p]]=[M[p],M[c]];const v=M[c][c];for(let j=c;j<=n;j++)M[c][j]/=v;for(let r=0;r<n;r++){if(r===c)continue;const f=M[r][c];for(let j=c;j<=n;j++)M[r][j]-=f*M[c][j]}}return M.map(r=>r[n])}
function stitch(arr){return new Promise(res=>{let imgs=[],loaded=0;arr.forEach((u,i)=>{const im=new Image();im.onload=()=>{imgs[i]=im;if(++loaded===arr.length){const W=Math.max(...imgs.map(x=>x.width)),H=imgs.reduce((s,x)=>s+x.height+18,0),c=ui.work,x=c.getContext('2d');c.width=W;c.height=H;x.fillStyle='#eee';x.fillRect(0,0,W,H);let y=0;imgs.forEach(im=>{x.drawImage(im,(W-im.width)/2,y);y+=im.height+18});res(c.toDataURL('image/jpeg',.9))}};im.src=u})})}
function openForm(){ui.preview.src=current;ui.date.valueAsDate=new Date();ui.amount.value='';ui.desc.value='';ui.notes.value='';ui.sheet.classList.add('on')}
function saveExpense(){const a=parseFloat(ui.amount.value),d=ui.desc.value.trim();if(!a||!d)return showToast('Vul bedrag en beschrijving in');expenses.unshift({id:Date.now(),date:ui.date.value,amount:a,desc:d,cat:ui.cat.value,notes:ui.notes.value,img:current});localStorage.visaExpenses=JSON.stringify(expenses);ui.sheet.classList.remove('on');render();showToast('Uitgave toegevoegd')}
function render(){ui.total.textContent='EUR '+expenses.reduce((s,e)=>s+Number(e.amount),0).toFixed(2);ui.list.innerHTML=expenses.length?expenses.map(e=>`<article class="expense"><div class="row"><div class="thumb">${e.img?`<img src="${e.img}">`:'Doc'}</div><div class="body"><div class="line1"><div class="desc">${esc(e.desc)}</div><div class="amt">EUR ${Number(e.amount).toFixed(2)}</div></div><div class="meta">${fmt(e.date)}</div><span class="cat">${esc(e.cat)}</span>${e.notes?`<div class="note">${esc(e.notes)}</div>`:''}</div></div><button class="del" onclick="deleteExpense(${e.id})">Verwijderen</button></article>`).join(''):'<div class="empty">Nog geen uitgaven</div>'}
function deleteExpense(id){expenses=expenses.filter(e=>e.id!==id);localStorage.visaExpenses=JSON.stringify(expenses);render()}
function fmt(d){if(!d)return'';const p=d.split('-');return p.length===3?`${p[2]}/${p[1]}/${p[0]}`:d}function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function exportPdf(){if(!expenses.length)return showToast('Geen uitgaven');const{jsPDF}=window.jspdf,doc=new jsPDF();expenses.forEach((e,i)=>{if(i)doc.addPage();doc.text(e.desc,10,15);doc.text('EUR '+Number(e.amount).toFixed(2),10,25);doc.text(e.cat,10,35);if(e.img)doc.addImage(e.img,'JPEG',10,45,180,120)});doc.save('visatracker.pdf')}
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
